In [18]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

def calc_N_deriv_local_kinpt(xi_int, eta_int, zeta_int):
    N_deriv_local_kinpt = np.zeros((3, 8))
    
    # derivative d(Ni)/d(xi_int)
    N_deriv_local_kinpt[0, 0] = -0.125 * (1.0 - eta_int) * (1.0 - zeta_int)
    N_deriv_local_kinpt[0, 1] =  0.125 * (1.0 - eta_int) * (1.0 - zeta_int)
    N_deriv_local_kinpt[0, 2] =  0.125 * (1.0 + eta_int) * (1.0 - zeta_int)
    N_deriv_local_kinpt[0, 3] = -0.125 * (1.0 + eta_int) * (1.0 - zeta_int)
    N_deriv_local_kinpt[0, 4] = -0.125 * (1.0 - eta_int) * (1.0 + zeta_int)
    N_deriv_local_kinpt[0, 5] =  0.125 * (1.0 - eta_int) * (1.0 + zeta_int)
    N_deriv_local_kinpt[0, 6] =  0.125 * (1.0 + eta_int) * (1.0 + zeta_int)
    N_deriv_local_kinpt[0, 7] = -0.125 * (1.0 + eta_int) * (1.0 + zeta_int)

    # derivative d(Ni)/d(eta_int)
    N_deriv_local_kinpt[1, 0] = -0.125 * (1.0 - xi_int) * (1.0 - zeta_int)
    N_deriv_local_kinpt[1, 1] = -0.125 * (1.0 + xi_int) * (1.0 - zeta_int)
    N_deriv_local_kinpt[1, 2] =  0.125 * (1.0 + xi_int) * (1.0 - zeta_int)
    N_deriv_local_kinpt[1, 3] =  0.125 * (1.0 - xi_int) * (1.0 - zeta_int)
    N_deriv_local_kinpt[1, 4] = -0.125 * (1.0 - xi_int) * (1.0 + zeta_int)
    N_deriv_local_kinpt[1, 5] = -0.125 * (1.0 + xi_int) * (1.0 + zeta_int)
    N_deriv_local_kinpt[1, 6] =  0.125 * (1.0 + xi_int) * (1.0 + zeta_int)
    N_deriv_local_kinpt[1, 7] =  0.125 * (1.0 - xi_int) * (1.0 + zeta_int)

    # derivative d(Ni)/d(zeta_int)
    N_deriv_local_kinpt[2, 0] = -0.125 * (1.0 - xi_int) * (1.0 - eta_int)
    N_deriv_local_kinpt[2, 1] = -0.125 * (1.0 + xi_int) * (1.0 - eta_int)
    N_deriv_local_kinpt[2, 2] = -0.125 * (1.0 + xi_int) * (1.0 + eta_int)
    N_deriv_local_kinpt[2, 3] = -0.125 * (1.0 - xi_int) * (1.0 + eta_int)
    N_deriv_local_kinpt[2, 4] =  0.125 * (1.0 - xi_int) * (1.0 - eta_int)
    N_deriv_local_kinpt[2, 5] =  0.125 * (1.0 + xi_int) * (1.0 - eta_int)
    N_deriv_local_kinpt[2, 6] =  0.125 * (1.0 + xi_int) * (1.0 + eta_int)
    N_deriv_local_kinpt[2, 7] =  0.125 * (1.0 - xi_int) * (1.0 + eta_int)

    return N_deriv_local_kinpt

# Coordinates for integration points (xi, eta, zeta)
integration_points = np.array([
    [-1/np.sqrt(3), -1/np.sqrt(3), -1/np.sqrt(3)],
    [ 1/np.sqrt(3), -1/np.sqrt(3), -1/np.sqrt(3)],
    [-1/np.sqrt(3),  1/np.sqrt(3), -1/np.sqrt(3)],
    [ 1/np.sqrt(3),  1/np.sqrt(3), -1/np.sqrt(3)],
    [-1/np.sqrt(3), -1/np.sqrt(3),  1/np.sqrt(3)],
    [ 1/np.sqrt(3), -1/np.sqrt(3),  1/np.sqrt(3)],
    [-1/np.sqrt(3),  1/np.sqrt(3),  1/np.sqrt(3)],
    [ 1/np.sqrt(3),  1/np.sqrt(3),  1/np.sqrt(3)]
])

# Calculate N_deriv_local_kinpt for each integration point
N_deriv_local_kinpt_list = [calc_N_deriv_local_kinpt(*pt) for pt in integration_points]
all_N_deriv_local_kinpt = np.array(N_deriv_local_kinpt_list)

print(all_N_deriv_local_kinpt.shape)

(8, 3, 8)


In [16]:
# Restructure the dataframe as per the requirement
N_deriv_local_kinpt_dict = {}

for idx, kinpt in enumerate(N_deriv_local_kinpt_list, 1):
    N_deriv_local_kinpt_dict[f'kinpt {idx}'] = kinpt.T.reshape(-1)  # Flatten each kinpt for easier display

# Create a new dataframe where each column represents a kinpt
df_N_deriv = pd.DataFrame(N_deriv_local_kinpt_dict)

# Create row labels for dimensions and nodes
dim_node_labels = [f'dim {d+1} - node {n+1}' for d in range(3) for n in range(8)]
df_N_deriv.index = dim_node_labels

# Save the results to a CSV file
df_N_deriv.to_excel('N_deriv_local_kinpt.xlsx', engine='openpyxl')

In [21]:
# Define the dimensions and node data
ndim = 3
nnode = 8

# Coordinates data
coords = np.array([
    [ 5.000000500000000E-004,  5.000000500000000E-004, -5.000000000000000E-004],
    [ 5.000000500000000E-004, -5.000000000000000E-004, -5.000000000000000E-004],
    [ 5.000000500000000E-004, -5.000000000000000E-004,  5.000000500000000E-004],
    [ 5.000000500000000E-004,  5.000000500000000E-004,  5.000000500000000E-004],
    [-4.999999525025496E-004,  5.000000500000000E-004, -5.000000000000000E-004],
    [-4.999999525025496E-004, -5.000000000000000E-004, -5.000000000000000E-004],
    [-4.999999525025496E-004, -5.000000000000000E-004,  5.000000500000000E-004],
    [-4.999999525025496E-004,  5.000000500000000E-004,  5.000000500000000E-004]
]).T  # transpose to shape (3, 8)

print(coords.shape)

(3, 8)


In [39]:
all_N_deriv_global_kinpt = np.zeros((8, 3, 8))
total_N_bar_deriv_global = np.zeros((ndim, nnode))

vol_el = 0.0

weights = [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

for kinpt in range(8):

    N_deriv_local_kinpt = all_N_deriv_local_kinpt[kinpt]
    # print(N_deriv_local_kinpt.shape)
    # Calculate the Jacobian matrix
    xjac = np.zeros((ndim, ndim))
    for inode in range(nnode):
        for idim in range(ndim):
            for jdim in range(ndim):
                xjac[jdim, idim] += N_deriv_local_kinpt[jdim, inode] * coords[idim, inode]

    # Calculate the determinant of the Jacobian
    djac = np.linalg.det(xjac)
    dvol = djac * weights[kinpt]

    # Calculate the inverse of the Jacobian matrix
    xjaci = np.linalg.inv(xjac)

    N_deriv_global_kinpt = np.dot(xjaci, N_deriv_local_kinpt)
    all_N_deriv_global_kinpt[kinpt, :, :] = N_deriv_global_kinpt

    for knode in range(nnode):
        for kdim in range(ndim):
            total_N_bar_deriv_global[kdim,knode] = total_N_bar_deriv_global[kdim,knode]\
                + N_deriv_global_kinpt[kdim,knode] * dvol

    vol_el = vol_el + dvol

    print(f'\nkinpt {kinpt+1}:')
    print('Jacobian matrix:')
    print(xjac)
    print('djac:', djac)
    print('Inverse Jacobian matrix:')
    print(xjaci)
    print('N_deriv_global_kinpt:')
    print(N_deriv_global_kinpt)
    print('dvol:', dvol)






kinpt 1:
Jacobian matrix:
[[ 0.00000000e+00 -5.00000025e-04  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  5.00000025e-04]
 [-5.00000001e-04 -6.77626358e-21  0.00000000e+00]]
djac: 1.250000128128193e-10
Inverse Jacobian matrix:
[[ 2.71050529e-14 -0.00000000e+00 -1.99999999e+03]
 [-1.99999990e+03 -0.00000000e+00 -0.00000000e+00]
 [ 0.00000000e+00  1.99999990e+03  0.00000000e+00]]
N_deriv_global_kinpt:
[[ 622.00846637  166.66666625   44.65819863  166.66666625 -622.00846637
  -166.66666625  -44.65819863 -166.66666625]
 [ 622.00843683 -622.00843683 -166.66665833  166.66665833  166.66665833
  -166.66665833  -44.65819651   44.65819651]
 [-622.00843683 -166.66665833  166.66665833  622.00843683 -166.66665833
   -44.65819651   44.65819651  166.66665833]]
dvol: 1.250000128128193e-10

kinpt 2:
Jacobian matrix:
[[ 0.00000000e+00 -5.00000025e-04  0.00000000e+00]
 [ 6.77626358e-21  6.77626358e-21  5.00000025e-04]
 [-5.00000001e-04 -6.77626358e-21  0.00000000e+00]]
djac: 1.250000128128193e-10
I

In [42]:
omega = 0.0

u_current = np.zeros(24)
du_current = np.zeros(24)

print('vol_el = ', vol_el)

# convert this fortran code to py

for knode in range(nnode):
    for kdim in range(ndim):
        N_bar_deriv_global[kdim, knode] = total_N_bar_deriv_global[kdim, knode] / (3.0 * vol_el)
        omega = omega + N_bar_deriv_global[kdim, knode] * u_current[ndim * knode - ndim + kdim]

print('omega = ', omega)
print('N_bar_deriv_global:')
print(N_bar_deriv_global)

vol_el =  1.0000001025025544e-09
omega =  0.0
N_bar_deriv_global:
[[ 83.33333312  83.33333312  83.33333312  83.33333312 -83.33333312
  -83.33333312 -83.33333312 -83.33333312]
 [ 83.33332917 -83.33332917 -83.33332917  83.33332917  83.33332917
  -83.33332917 -83.33332917  83.33332917]
 [-83.33332917 -83.33332917  83.33332917  83.33332917 -83.33332917
  -83.33332917  83.33332917  83.33332917]]
