In [5]:
import numpy as np
from scipy.linalg import logm

# Define the test matrices
matrices = {
    'Identity Matrix': np.eye(3),
    #'Zero Matrix': np.zeros((3, 3)),
    'Symmetric Matrix': np.array([[2, 1, 0], [1, 2, 1], [0, 1, 2]]),
    'Unsymmetric Matrix': np.array([[0, 2, 1], [1, 1, 1], [2, 0, 3]]),
    #'Matrix with Zero Eigenvalue': np.array([[0, 1, 0], [0, 0, 1], [0, 0, 0]])  # Jordan block
}

# Perform the matrix log and handle cases where log is undefined
for name, matrix in matrices.items():
    try:
        matrix_log = logm(matrix)
        print(f"\n{name}:")
        print(matrix)
        print("Logarithm of the matrix:")
        print(matrix_log)
    except ValueError as e:
        print(f"\n{name}:\nMatrix log not defined. Error: {e}")



Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Logarithm of the matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Symmetric Matrix:
[[2 1 0]
 [1 2 1]
 [0 1 2]]
Logarithm of the matrix:
[[ 0.51986039  0.62322524 -0.1732868 ]
 [ 0.62322524  0.34657359  0.62322524]
 [-0.1732868   0.62322524  0.51986039]]

Unsymmetric Matrix:
[[0 2 1]
 [1 1 1]
 [2 0 3]]
Logarithm of the matrix:
[[0.27725887+2.51327412e+00j 0.18483925-2.51327412e+00j
  0.46209812+1.99239516e-16j]
 [0.27725887-6.28318531e-01j 0.18483925+6.28318531e-01j
  0.46209812-8.78660190e-18j]
 [0.55451774-1.25663706e+00j 0.3696785 +1.25663706e+00j
  0.92419624-6.44569491e-17j]]


In [4]:
import math

def matrix_multiply(A, B):
    """Multiplies two matrices A and B."""
    result = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    return result

def matrix_subtract(A, B):
    """Subtracts matrix B from matrix A."""
    result = [[A[i][j] - B[i][j] for j in range(len(A[0]))] for i in range(len(A))]
    return result

def matrix_add(A, B):
    """Adds two matrices A and B."""
    result = [[A[i][j] + B[i][j] for j in range(len(A[0]))] for i in range(len(A))]
    return result

def scalar_multiply_matrix(scalar, A):
    """Multiplies a matrix A by a scalar value."""
    result = [[scalar * A[i][j] for j in range(len(A[0]))] for i in range(len(A))]
    return result

def identity_matrix(size):
    """Creates an identity matrix of given size."""
    return [[1 if i == j else 0 for j in range(size)] for i in range(size)]

def matrix_log(A, iterations=100000):
    """Approximates the matrix logarithm using a series expansion."""
    n = len(A)
    I = identity_matrix(n)  # Identity matrix
    X = matrix_subtract(A, I)  # X = A - I
    
    current_term = X  # Start with X^1
    log_A = current_term  # Initialize log(A) with the first term

    for k in range(2, iterations + 1):
        current_term = matrix_multiply(current_term, X)  # Compute X^k
        term = scalar_multiply_matrix((-1) ** (k + 1) / k, current_term)  # Compute (-1)^(k+1) * X^k / k
        log_A = matrix_add(log_A, term)  # Add the term to the result

    return log_A

# Example matrices
identity = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
zeros_matrix = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
symmetric_matrix = [[4, 1, 2], [1, 3, 0], [2, 0, 5]]
unsymmetric_matrix = [[0, 2, 1], [1, 1, 1], [2, 0, 3]]
matrix_with_zero_eigenvalue = [[1, 1, 0], [0, 0, 0], [0, 0, 2]]

# Compute matrix logarithms
print("Logarithm of identity matrix:")
print(matrix_log(identity))

print("\nLogarithm of zeros matrix (not defined):")
print(matrix_log(zeros_matrix))

print("\nLogarithm of symmetric matrix:")
print(matrix_log(symmetric_matrix))

print("\nLogarithm of unsymmetric matrix:")
print(matrix_log(unsymmetric_matrix))

print("\nLogarithm of matrix with zero eigenvalue:")
print(matrix_log(matrix_with_zero_eigenvalue))


Logarithm of identity matrix:
[[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]]

Logarithm of zeros matrix (not defined):
[[-12.090146129863335, 0.0, 0.0], [0.0, -12.090146129863335, 0.0], [0.0, 0.0, -12.090146129863335]]

Logarithm of symmetric matrix:


OverflowError: int too large to convert to float