In [4]:
import numpy as np
from scipy.linalg import sqrtm, sqrtm, inv, logm, expm, norm

# Example symmetric positive definite matrix (3x3)
A = np.array([[4.0, 1.0, 1.0],
              [1.0, 3.0, 0.5],
              [1.0, 0.5, 2.0]])

# Compute matrix square root using SciPy
A_sqrt = sqrtm(A)

# Verify that sqrt(A) * sqrt(A) ≈ A
A_reconstructed = A_sqrt @ A_sqrt

# Tolerance check
tol = 1e-10

# Check difference
error = norm(A_reconstructed - A)

print("Original Matrix A:\n", A)
print("\nComputed sqrt(A):\n", A_sqrt.real)
print("\nReconstructed A from sqrt:\n", A_reconstructed.real)
print(f"\nError (Frobenius norm): {error:.6e}")


if error < tol:
    print("\n✅ Sqrt test passed.")
else:
    print("\n❌ Sqrt test failed.")

# Compute inverse
A_inv = inv(A)
identity_from_inv = A_inv @ A
error_inv = norm(identity_from_inv - np.eye(3))

print("\nInverse of A:\n", A_inv.real)
print("\nA_inv * A:\n", identity_from_inv.real)
print(f"Inverse Error (should be near zero): {error_inv:.6e}")

if error_inv < tol:
    print("\n✅ Inverse test passed.")
else:
    print("\n❌ Inverse test failed.")

# Compute matrix log and exp(log)
A_log = logm(A)
A_reconstructed_log = expm(A_log)
error_log = norm(A_reconstructed_log - A)

print("\nlogm(A):\n", A_log.real)
print("\nexp(logm(A)):\n", A_reconstructed_log.real)
print(f"Logarithm Error (should be near zero): {error_log:.6e}")

if error_log < tol:
    print("✅ Logarithm test passed.")
else:
    print("❌ Logarithm test failed.")


Original Matrix A:
 [[4.  1.  1. ]
 [1.  3.  0.5]
 [1.  0.5 2. ]]

Computed sqrt(A):
 [[1.96166666 0.26177743 0.2886806 ]
 [0.26177743 1.70661502 0.13761451]
 [0.2886806  0.13761451 1.37757967]]

Reconstructed A from sqrt:
 [[4.  1.  1. ]
 [1.  3.  0.5]
 [1.  0.5 2. ]]

Error (Frobenius norm): 4.681404e-15

✅ Sqrt test passed.

Inverse of A:
 [[ 0.30263158 -0.07894737 -0.13157895]
 [-0.07894737  0.36842105 -0.05263158]
 [-0.13157895 -0.05263158  0.57894737]]

A_inv * A:
 [[ 1.00000000e+00  1.38777878e-17  0.00000000e+00]
 [-6.93889390e-18  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
Inverse Error (should be near zero): 1.551584e-17

✅ Inverse test passed.

logm(A):
 [[1.30226307 0.27652416 0.34291303]
 [0.27652416 1.04233613 0.1548593 ]
 [0.34291303 0.1548593  0.59983978]]

exp(logm(A)):
 [[4.  1.  1. ]
 [1.  3.  0.5]
 [1.  0.5 2. ]]
Logarithm Error (should be near zero): 4.242156e-15
✅ Logarithm test passed.
